### ISSUE TITLE
Software requirements document revision

### ISSUE THREAD

**Issue by igrangel** [BonnWestCoast/Semantify.io-docs#1]
1. In the general description should be included a paragraph saying what is OPC UA and maybe a reference. 
2. The use case "Identify Malformed XML" still contains the typo SOA OPC schema. 
3. The description (English) of the SPARQL queries use case support should be re - made. 
4. The non - functional handle different format files should contain more files that those that currently have. 
5. The use case "Handle Large files" still contains the typo SOA OPC schema. Here we need to declare what are "large files" for us because this impacts the escalability of our system. 
6. We need to perform "stress test" to determine the limits of our system. 
7. For the responsive interface - are you planning to use Twitter Bootstrap? I strongly recommend it. 
8. In the Use case templates I don´t think that any of the descriptions are self-explained.
9. We need to iterate and improve the use cases understanding and its descriptions.

**Comment by shinhokang** [comment]
"1. About the description of OPC UA : I will write and organize it in other document, so Omar you can copy it when I complete it.

"4. maybe we can add ".owx, .owl" for owl, ".nt" for N-triple, anything else?

**Comment by igrangel** [comment]
1. Please, check for the RDF/OWL serializations (ttl, owl, omn, nt, etc). You should Include all of them.

**Comment by trinogz** [comment]
Ok, thanks. I will update the file tonight

**Comment by trinogz** [comment]
1. I included some intro about i4.0 and M2M concepts. And I did mention of OPC UA. I will wait for the document that Shinho will create. I have a question. Is good idea include references to Wikipedia?
   2, 3 and 4 fixed.
2. What I meant with "large files" was "files with a big number of triples". I modified the concept.
3. Where to include the information about the "stress tests"?
4. I agree about Bootstrap, I included on the tools in the document.
5. I included a description, what I wanted to avoid is the redundancy of information. For example, IMO it is not necessary to describe that you will upload a file to the system.

**Comment by igrangel** [comment]
1. It is not a good idea to include references from Wikipedia. References should be taken from the webpages of the Standards or from papers. 
2. "Large files" and "files with a big number of triples" is a pretty similar sentence. How big? How many triples? Of course, this is not for the first phase but should be taken into account.
3. Our tool will contain an evaluation phase. There we should include the escalability issue with the stress test.
4. Ok
5. It is not the same to upload a word document, which is a file, than to upload an ontology. Therefore, in our case, should be described. This will help us a lot.

**Comment by trinogz** [comment]
1,  Shinho added the references.

2 and 3, I decided to limit the size file to 4 MB. However, what I was trying to express with "handle large files" was that the editor will be able to show only few triples at time, and refresh itself if the user needs to visualize more. Similar to show only 20 rows from a table, but this table has millions of rows. I think that this is related with the "stress tests".

4, I marked with red the requirement related with the responsive interface because it has not been discussed with the team.

5, Description improved.

**Comment by igrangel** [comment]
2, 3 - We can not "decide" the scalability of our tool in advance. As I said we should test it and, then, observe our limitations. So, for now, we should only say that we will provide test with this in mind. 

4 - This requirement is not functional but it should be included.
