### ISSUE TITLE
27. 04. 2016 Skype-Meeting and decided To Dos

### ISSUE THREAD

**Issue by shinhokang** [BonnWestCoast/Semantify.io-docs#2]
# Topic Selection & Project Title
- From Standards to Ontologies - A Web-based tool to semantify / ontologize the knowledge of a standards with semantic technologies
- Semantify.io
# General
- To decide Roles and Responsibilities of the member. Send it to Mr. Irlan. - **Shinho**
- Most of all, **every member should read updates of documents and share the idea.**
# Use-cases
- ~~To Modify some use-case title and relation. (done & checked in the meeting)~~ - **Alex**
  - 
- To complete the document for Use-cases presentation - **Alex**
- To write use-case descriptions for each of use-case - **Omar**
- To rewrite Pre-conditions and post-conditions. Pre-condition is more important in this step. - **Omar**
# Requirements
- To modify specific requirements - **Shinho & Omar**
  - Export ontology in **RDF/XML, Turtle, OWL, Manchester"
  - Divide 
- To write a mapping table which describes Mapping OPC UA nodes to OWL ontology - **Shinho & Alexey**
  - Refer to a article:Mapping XML to OWL Ontologies - http://www.informatik.uni-leipzig.de/~auer/publication/xml2owl.pdf
# Architecture Design
- ~~To draw a sequence diagram for the main process~~ - **Alex**
- ~~To modify back-end part - e.g. labelling tech, grouping, connection (done & checked in the meeting)~~ - **Alex**
# Preparing Implementation
- Find and test libraries - **Alexey**
  - _Do we have organized result of this task?_ if not, please refer this link - https://docs.google.com/spreadsheets/d/1akGsEl52Be9l7TUYlQNFlkaN63H9KATidVnJ8nbaRMU/edit#gid=976849111

**Comment by trinogz** [comment]
- Use-case descriptions for the use-cases.
- Preconditions were improved.
- Table of requirements was divided.

Doing the use-case descriptions, I was thinking that **`Upload` and `Create` are basically the same thing** because in the process of uploading the OPC to OWL translation is executed. Am I am wrong? 

Or we can upload and store the Schema and instances files to be used later? IMO we can have a use-case `Create` including the other use-case `Upload`.

**Comment by igrangel** [comment]
1. To my understanding, _Upload_ is the process of browsing for **OPC UA** file, locating it from the computer or from the Web url and bringing it to our system. Within this process the _validation_ against the **OPC UA** schema should be made. Keep in mind that we should _know_ when we are dealing with an **OPC UA** schema file or an instance file. 
2. The _Create_ will be, after this process performed correctly, the translation to an OWL ontology.
