### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by igrangel** [BonnWestCoast/Semantify.io-docs#3]
1 - All the slides should contain a title and a number
2 - Validate XSD/XML files with respect to what?
3 - The slides with important content should contain explanations. If someone of you is missing the other can make the presentation

**Comment by trinogz** [comment]
1. Done.
2. Done.
3. I added more information, I added also some notes. I decided not to fill the slides with a lot of text to avoid overloaded slides. Please, give me a new feed back about this.

Other details:
1. The provisional name I chose: OPC Semantifier. 
2. I added an slide to give again a brief preview about the project.

Is there another **requirement** that perhaps I am ignoring?
